branches:
  only:
    - dev-master
    - travis-unit-tests
language: python
compiler:
  - gcc
python:
  - "2.6"
env:
  - NUPIC=$TRAVIS_BUILD_DIR

notifications:
  irc: 
    channels: 
      - "irc.freenode.net#nupic"
  webhooks: http://issues.numenta.org:8081/travis

before_install:
  - "source $NUPIC/env.sh"

install: "$NUPIC/build.sh"

# Not working yet.
before_script: 
  - "echo $NTA"
  - "ls $NTA"
  - "ls $NTA/bin"
script: "$NTA/bin/testeverything"
