branches:
  only:
    - dev-master
    - travis-unit-tests
language: python
compiler:
  - gcc
python:
  - "2.6"
env:
  global:
    - NUPIC=$TRAVIS_BUILD_DIR
    - NTA=$HOME/nta/eng

notifications:
  irc: 
    channels: 
      - "irc.freenode.net#nupic"
  webhooks: http://issues.numenta.org:8081/travis

before_install:
  - "source $NUPIC/env.sh"

install: "$NUPIC/build.sh"

# Not working yet.
script: "$NTA/bin/testeverything"
