branches:
  only:
    - dev-master
language: python
compiler:
  - gcc
python:
  - "2.6"
env:
  - NUPIC=$TRAVIS_BUILD_DIR

before_install:
  - "source $NUPIC/env.sh"
install: "$NUPIC/build.sh"

# dummy tests for now
script: "banner FAKED"

after_success:
  - "cd $NUPIC"
  - "git fetch origin"
  - "git merge origin/master"