branches:
  only:
    - dev-master
language: python
compiler:
  - gcc
python:
  - "2.6"
env:
  - NUPIC=$TRAVIS_BUILD_DIR

notifications:
  irc: "irc.freenode.net#nupic"
    - on_start: true
  webhooks: http://issues.numenta.org:8081/travis

before_install:
  - "source $NUPIC/env.sh"
install: "$NUPIC/build.sh"

# dummy tests for now
script: "pwd"

after_success:
  - "echo yay!"
